import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const funds=["000001","000011","000751","001044","001410","001714","001875","001938","002190","003095","005827","110022","161725","163406","163417","166002","260108","519674","519736","270002"];
const headers={"user-agent":"Mozilla/5.0 (compatible; FundPositionLens/1.0; public-disclosure-aggregator)",referer:"https://fundf10.eastmoney.com/"};
const clean=s=>s.replaceAll("&amp;","&").replace(/<[^>]+>/g,"").trim();
function parse(text,fundCode){const out=[];for(const sec of text.matchAll(/截止至：<font class='px12'>(\d{4}-\d{2}-\d{2})<\/font>[\s\S]*?<tbody>([\s\S]*?)<\/tbody>/g)){for(const rm of sec[2].matchAll(/<tr>([\s\S]*?)<\/tr>/g)){const r=rm[1],c=r.match(/unify\/r\/[01]\.(\d{6})'>(\d{6})<\/a>/),n=r.match(/<td class='tol'><a[^>]*>([^<]+)<\/a>/),w=r.match(/<td class='tor'>([\d.]+)%<\/td>/);if(c&&n&&w)out.push({fundCode,endDate:sec[1],code:c[1],name:clean(n[1]),weight:+w[1]})}}return out}
async function fundYear(code,year){const u=new URL("https://fundf10.eastmoney.com/FundArchivesDatas.aspx");Object.entries({type:"jjcc",code,topline:"10",year:String(year),month:"",rt:String(Date.now())}).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u,{headers});if(!r.ok)throw new Error(`${code}: ${r.status}`);return parse(await r.text(),code)}
async function industries(){const u=new URL("https://82.push2.eastmoney.com/api/qt/clist/get");Object.entries({pn:"1",pz:"6000",po:"1",np:"1",fltt:"2",invt:"2",fid:"f3",fs:"m:0+t:6,m:0+t:80,m:1+t:2,m:1+t:23",fields:"f12,f14,f100"}).forEach(([k,v])=>u.searchParams.set(k,v));const j=await(await fetch(u,{headers})).json();return new Map((j.data?.diff||[]).map(x=>[x.f12,{name:x.f14,industry:x.f100||"未分类"}]))}
function snap(rows,date){const d=new Map;for(const r of rows)if(r.endDate<=date&&r.endDate>(d.get(r.fundCode)||""))d.set(r.fundCode,r.endDate);return rows.filter(r=>d.get(r.fundCode)===r.endDate)}
function agg(cur,base,stocks){const sum=rows=>{const m=new Map;for(const r of rows){const v=m.get(r.code)||{name:r.name,weight:0,funds:new Set};v.weight+=r.weight;v.funds.add(r.fundCode);m.set(r.code,v)}return m},a=sum(cur),b=sum(base);return [...a].map(([code,v])=>({code,name:stocks.get(code)?.name||v.name,weight:+v.weight.toFixed(2),funds:v.funds.size,change:+(v.weight-(b.get(code)?.weight||0)).toFixed(2),sector:stocks.get(code)?.industry||"未分类"})).sort((x,y)=>y.change-x.change||y.weight-x.weight).slice(0,20)}
const now=new Date,years=[now.getFullYear(),now.getFullYear()-1],settled=await Promise.allSettled(funds.flatMap(f=>years.map(y=>fundYear(f,y)))),rows=settled.flatMap(x=>x.status==="fulfilled"?x.value:[]),stocks=await industries();if(!rows.length)throw new Error("No disclosure rows");const latest=rows.reduce((a,r)=>r.endDate>a?r.endDate:a,""),cur=snap(rows,latest),iso=d=>d.toISOString().slice(0,10),targets=[{id:"week",label:"近1周",subtitle:"公开披露快照 · 周度对比",date:new Date(now-7*864e5)},{id:"month",label:"近1月",subtitle:"公开披露快照 · 月度对比",date:new Date(now-30*864e5)},{id:"year",label:"今年以来",subtitle:"公开披露快照 · 年初对比",date:new Date(now.getFullYear(),0,1)}];const payload={mode:"live",source:"天天基金公开披露 · 东方财富行业分类",fetchedAt:now.toISOString(),latestDisclosure:latest,coverage:{funds:funds.length,successfulRequests:settled.filter(x=>x.status==="fulfilled").length,snapshots:rows.length},periods:targets.map(p=>({...p,date:undefined,data:agg(cur,snap(rows,iso(p.date)),stocks)}))};await writeFile(resolve("data.json"),JSON.stringify(payload,null,2)+"\n");console.log(`updated ${rows.length} snapshots`);
